In [0]:
from sklearn.cluster import KMeans
import numpy as np

In [0]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [4, 2], [4, 4], [4, 0]])

In [0]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [8]:
# クラスタリング後の結果の表示
kmeans.labels_

array([0, 0, 0, 1, 1, 1], dtype=int32)

In [9]:
# テストデータによる予測
kmeans.predict([[0, 0], [4, 4]])

array([0, 1], dtype=int32)

In [10]:
# クラスターの重心の表示
kmeans.cluster_centers_

array([[1., 2.],
       [4., 2.]])

In [0]:
# DBSCAN

In [0]:
from sklearn.cluster import DBSCAN
import numpy as np

In [0]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [4, 2], [4, 4], [4, 0]])

In [0]:
dbscan = DBSCAN(eps=3, min_samples=2).fit(X)

In [27]:
# クラスタリング後の結果の表示
dbscan.labels_

array([0, 0, 0, 0, 0, 0])

In [28]:
dbscan.fit_predict([[0, 0], [4, 4]])

array([-1, -1])

In [29]:
dbscan.get_params

<bound method BaseEstimator.get_params of DBSCAN(algorithm='auto', eps=3, leaf_size=30, metric='euclidean',
    metric_params=None, min_samples=2, n_jobs=None, p=None)>

In [0]:
dbscan = DBSCAN(eps=2, min_samples=1).fit(X)

In [37]:
# クラスタリング後の結果の表示
dbscan.labels_

array([0, 0, 0, 1, 1, 1])

In [38]:
dbscan.fit_predict([[0, 0], [4, 4]])

array([0, 1])