In [0]:
import numpy as np

In [0]:
A = np.array([1, 0, 4, 0, 1, 6, 8, 7, 4])

In [4]:
A.reshape(3, 3)

array([[1, 0, 4],
       [0, 1, 6],
       [8, 7, 4]])

In [0]:
A = np.array([[7, 5, 3, 5, 1, 5],
            [2, 1, 7, 4, 3, 7],
            [4, 7, 3, 2, 1, 8],
            [0, 0, 2, 7, 0, 2],
            [5, 5, 3, 5, 4, 6],
            [5, 2, 1, 1, 7, 4]])
B = A[3:][:]

In [7]:
B

array([[0, 0, 2, 7, 0, 2],
       [5, 5, 3, 5, 4, 6],
       [5, 2, 1, 1, 7, 4]])

In [13]:
A = np.array([[5, 3, 5, 0, 8, 0],
       [0, 1, 0, 0, 2, 0],
       [2, 8, 4, 5, 8, 4],
       [8, 3, 2, 1, 1, 0],
       [2, 2, 1, 4, 7, 4]])
B = A[:3][:]
B

array([[5, 3, 5, 0, 8, 0],
       [0, 1, 0, 0, 2, 0],
       [2, 8, 4, 5, 8, 4]])

In [9]:
A = np.array([[6, 2, 1],
       [1, 1, 0],
       [0, 0, 5],
       [6, 2, 5]])
B = A.T
B

array([[6, 1, 0, 6],
       [2, 1, 0, 2],
       [1, 0, 5, 5]])

In [11]:
A = np.array([4, 5, 5, 2, 1, 3, 2, 3, 0, 6, 4, 6, 0, 4, 4])
B = A.reshape(5, 3)
B

array([[4, 5, 5],
       [2, 1, 3],
       [2, 3, 0],
       [6, 4, 6],
       [0, 4, 4]])

In [15]:
A = np.array([7, 6, 6, 3, 1, 8, 0, 6, 5, 7, 8, 2])
B = A.reshape(3, 4)
B

array([[7, 6, 6, 3],
       [1, 8, 0, 6],
       [5, 7, 8, 2]])

In [16]:
A = np.array([0, 0, 4, 8, 0, 5, 6, 4, 1, 0, 2, 4])
B = A.reshape(3, 4)
B

array([[0, 0, 4, 8],
       [0, 5, 6, 4],
       [1, 0, 2, 4]])

In [81]:
np.ravel(r_[A, A][:7])

NameError: ignored

In [20]:
A = np.array([3, 6, 5, 4, 6, 4, 7])
B = np.sort(A)
B

array([3, 4, 4, 5, 6, 6, 7])

In [69]:
A = np.array([[2],
       [2],
       [6],
       [7]])

A1 = A.flatten()
A1

array([2, 2, 6, 7])

In [80]:
np.ravel(np.r_[A, A][:7])

np.ravel(np.r_[A, A][:7])

array([2, 2, 6, 7, 2, 2, 6])

In [96]:
A = np.array([[2],
       [2],
       [6],
       [7]])

C = A.ravel()
np.r_[C, C][:7]

array([2, 2, 6, 7, 2, 2, 6])

In [95]:
A = np.array([[2],
       [2],
       [6],
       [7]])
np.r_[A, A]

array([[2],
       [2],
       [6],
       [7],
       [2],
       [2],
       [6],
       [7]])

In [83]:
np.r_[A, A][:7].reshape(-1,)

array([2, 2, 6, 7, 2, 2, 6])

In [63]:
np.hstack((A1,A1[:3]))

array([2, 2, 6, 7, 2, 2, 6])

In [0]:
A2 = A1[:3]

In [54]:
np.concatenate([A1, A2])

array([2, 2, 6, 7, 2, 2, 6])

In [48]:
np.vstack((A1, A1[:2]))

ValueError: ignored

In [24]:
A = np.array([7, 2, 7, 2, 6, 6, 5])
B = np.sort(A)
B

array([2, 2, 5, 6, 6, 7, 7])

In [26]:
A = np.array([[20, 40, 20, 70, 40, 90, 70],
       [50, 50, 70, 50, 20, 20, 10],
       [70, 90, 50, 10, 40, 70, 30],
       [90, 40, 90, 10, 10, 60, 20],
       [50, 10, 10, 10, 20, 70, 80],
       [80, 30, 20, 10, 40, 80, 20],
       [40, 20, 60, 50, 80, 70, 80]])
B = np.array([[2, 8, 6, 8, 4, 3, 3]])

C = A + B
C

array([[22, 48, 26, 78, 44, 93, 73],
       [52, 58, 76, 58, 24, 23, 13],
       [72, 98, 56, 18, 44, 73, 33],
       [92, 48, 96, 18, 14, 63, 23],
       [52, 18, 16, 18, 24, 73, 83],
       [82, 38, 26, 18, 44, 83, 23],
       [42, 28, 66, 58, 84, 73, 83]])

In [27]:
A = np.array([[7, 7, 2, 6],
       [1, 5, 7, 1],
       [8, 8, 6, 1],
       [5, 5, 6, 8]])

B = np.array([[8, 1, 1, 4],
       [3, 5, 4, 4],
       [1, 7, 1, 7],
       [1, 3, 1, 6]])
C = A - B
C

array([[-1,  6,  1,  2],
       [-2,  0,  3, -3],
       [ 7,  1,  5, -6],
       [ 4,  2,  5,  2]])

In [28]:
A = np.array([3, 4, 2, 8, 7, 5, 4, 5, 8, 1, 6, 4, 3, 3, 4, 1, 6, 0, 7, 2])
A_1 = A * A
B = A_1.reshape(4, 5)
B

array([[ 9, 16,  4, 64, 49],
       [25, 16, 25, 64,  1],
       [36, 16,  9,  9, 16],
       [ 1, 36,  0, 49,  4]])

In [35]:
A = np.array([[0, 8, 5, 5, 4, 0, 3, 8],
       [2, 3, 3, 3, 0, 1, 2, 6],
       [1, 7, 8, 0, 3, 7, 4, 0],
       [0, 0, 3, 4, 2, 0, 6, 0],
       [3, 7, 7, 5, 7, 4, 5, 8],
       [8, 7, 8, 1, 2, 6, 7, 2],
       [0, 2, 3, 3, 0, 5, 5, 7],
       [7, 0, 0, 7, 2, 6, 6, 5]])
dA = np.diag(A) 
B = np.diag(dA)
B

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 0, 5]])

In [33]:
a5 = np.diag([1, 2, 3]); a5

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
A = np.array([[2, 6, 6, 7, 5, 6, 3],
       [5, 8, 2, 7, 4, 6, 2],
       [1, 2, 8, 3, 3, 6, 8],
       [4, 7, 7, 0, 7, 6, 8],
       [4, 6, 7, 1, 8, 3, 5]])
B = A.max(axis=0)

array([5, 8, 8, 7, 8, 6, 8])