In [0]:
!pip -q install gym

In [0]:
import gym
import numpy as np

In [0]:
env = gym.make('FrozenLake-v0')

In [0]:
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [6]:
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
lr = 0.8
y = 0.95
num_episodes = 2000
rList = []

In [0]:
for i in range(num_episodes):
  s = env.reset()
  rAll = 0
  d = False  # 穴に落ちたか？
  j = 0      # 穴に落ちた回数
  while j < 99:
    j += 1
    a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n)*(1.0/(i+1)))
    s1, r, d ,_ = env.step(a)
    Q[s,a] = Q[s,a] + lr * (r + y*np.max(Q[s1,:]) - Q[s,a])
    rAll += r
    s = s1
    if d == True:
      break
  rList.append(rAll)

In [10]:
print ("回数ごとの結果：" + str(sum(rList)/num_episodes))

回数ごとの結果：0.5605


In [12]:
print("最終的なQテーブルの値")
print(Q)

最終的なQテーブルの値
[[2.20999624e-01 1.01410981e-02 8.38233642e-03 1.02271205e-02]
 [2.13457084e-03 2.27591812e-03 7.64106807e-04 9.36201039e-02]
 [1.16950224e-01 8.72179393e-03 2.22517154e-03 7.85212025e-03]
 [2.54055357e-03 1.47418423e-03 3.17257600e-04 8.26458393e-03]
 [3.47633984e-01 3.97301960e-03 2.28412548e-03 8.34389166e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.90715460e-01 1.88073882e-05 9.47265248e-04 3.15778834e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.23913875e-04 1.18163782e-05 0.00000000e+00 4.57211191e-01]
 [9.74504717e-04 7.22135880e-01 0.00000000e+00 2.46174545e-04]
 [2.98819574e-01 0.00000000e+00 5.59672837e-04 2.18579928e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.15687464e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.73430661e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e