In [1]:
#movielens のデータセットのダウンロード
!wget "http://files.grouplens.org/datasets/movielens/ml-100k.zip"

--2019-12-06 06:21:51--  http://files.grouplens.org/datasets/movielens/ml-100k.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4924029 (4.7M) [application/zip]
Saving to: ‘ml-100k.zip’

ml-100k.zip         100%[===================>]   4.70M  12.7MB/s    in 0.4s    

2019-12-06 06:21:57 (12.7 MB/s) - ‘ml-100k.zip’ saved [4924029/4924029]



In [2]:
#ダウンロードデータの解凍
!unzip ml-100k.zip

Archive:  ml-100k.zip
   creating: ml-100k/
  inflating: ml-100k/allbut.pl       
  inflating: ml-100k/mku.sh          
  inflating: ml-100k/README          
  inflating: ml-100k/u.data          
  inflating: ml-100k/u.genre         
  inflating: ml-100k/u.info          
  inflating: ml-100k/u.item          
  inflating: ml-100k/u.occupation    
  inflating: ml-100k/u.user          
  inflating: ml-100k/u1.base         
  inflating: ml-100k/u1.test         
  inflating: ml-100k/u2.base         
  inflating: ml-100k/u2.test         
  inflating: ml-100k/u3.base         
  inflating: ml-100k/u3.test         
  inflating: ml-100k/u4.base         
  inflating: ml-100k/u4.test         
  inflating: ml-100k/u5.base         
  inflating: ml-100k/u5.test         
  inflating: ml-100k/ua.base         
  inflating: ml-100k/ua.test         
  inflating: ml-100k/ub.base         
  inflating: ml-100k/ub.test         


In [3]:
ls "ml-100k/"

allbut.pl*  u1.base  u2.test  u4.base  u5.test  ub.base  u.genre  u.occupation
mku.sh*     u1.test  u3.base  u4.test  ua.base  ub.test  u.info   u.user
README      u2.base  u3.test  u5.base  ua.test  u.data   u.item


In [0]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [0]:
d = pd.read_csv("ml-100k/u.data",sep='\t',names="user_id,item_id,rating,timestamp".split(","))

In [6]:
d.head()

user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [0]:
#ratingが3より大きいものを抜粋
d = d[d["rating"]>3]

In [8]:
d.head()

user_id  item_id  rating  timestamp
5       298      474       4  884182806
7       253      465       5  891628467
11      286     1014       5  879781125
12      200      222       5  876042340
16      122      387       5  879270459

In [9]:
d.rating.unique()

array([4, 5])

In [0]:
d.drop(labels=["timestamp"], axis=1, inplace=True)

In [11]:
d.head()

user_id  item_id  rating
5       298      474       4
7       253      465       5
11      286     1014       5
12      200      222       5
16      122      387       5

In [0]:
d.loc[:,"rating"] = 1

In [13]:
d.head()

user_id  item_id  rating
5       298      474       1
7       253      465       1
11      286     1014       1
12      200      222       1
16      122      387       1

In [14]:
d.rating.unique()

array([1])

In [15]:
d.shape

(55375, 3)

In [0]:
d.drop_duplicates(keep='first', inplace=True)

In [17]:
d.shape

(55375, 3)

In [18]:
d.head()

user_id  item_id  rating
5       298      474       1
7       253      465       1
11      286     1014       1
12      200      222       1
16      122      387       1

In [0]:
d = pd.pivot_table(d, values='rating', index='item_id', columns='user_id', aggfunc='sum', fill_value=0)

In [20]:
d.head()

user_id  1    2    3    4    5    6    7    ...  937  938  939  940  941  942  943
item_id                                     ...                                   
1          1    1    0    0    1    1    0  ...    0    1    0    0    1    0    0
2          0    0    0    0    0    0    0  ...    0    0    0    0    0    0    1
3          1    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4          0    0    0    0    0    0    1  ...    0    0    0    0    0    0    0
5          0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[5 rows x 942 columns]

In [0]:
d.reset_index(inplace=True)

In [22]:
d.head()

user_id  item_id  1  2  3  4  5  6  7  ...  936  937  938  939  940  941  942  943
0              1  1  1  0  0  1  1  0  ...    1    0    1    0    0    1    0    0
1              2  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    1
2              3  1  0  0  0  0  0  0  ...    1    0    0    0    0    0    0    0
3              4  0  0  0  0  0  0  1  ...    0    0    0    0    0    0    0    0
4              5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0

[5 rows x 943 columns]

In [0]:
#コサイン距離計算用の関数作成
def cosine_distance(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [0]:
#item_id=53の映画を選択し、その類似の映画を出力する
wanted_item = 53
search_item = d[d["item_id"]==wanted_item]

In [0]:
search_item

user_id  item_id  1  2  3  4  5  6  7  ...  936  937  938  939  940  941  942  943
52            53  0  0  0  0  0  0  1  ...    0    0    0    0    0    0    0    0

[1 rows x 943 columns]

In [0]:
search_item = search_item.iloc[0,1:].values

In [0]:
search_item

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [0]:
d.shape

(1447, 943)

In [0]:
#item_idがwanted_item以外を取得
others = d[~(d["item_id"]==wanted_item)]

In [0]:
others.shape

(1446, 943)

In [0]:
others.head()

user_id  item_id  1  2  3  4  5  6  7  ...  936  937  938  939  940  941  942  943
0              1  1  1  0  0  1  1  0  ...    1    0    1    0    0    1    0    0
1              2  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    1
2              3  1  0  0  0  0  0  0  ...    1    0    0    0    0    0    0    0
3              4  0  0  0  0  0  0  1  ...    0    0    0    0    0    0    0    0
4              5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0

[5 rows x 943 columns]

In [0]:
#二つの映画(item_id=53とそれ以外)ごとのコサイン距離を網羅的に計算する
#結果の入れ物(リスト)を作成
distance = []
#繰り返し回数は、othersの行数
num_iteration = others.shape[0]
for i in range(num_iteration):
    #二つの映画(item_id=53とそれ以外)のコサイン距離を計算する
    x = cosine_distance(search_item, others.iloc[i,1:].values)
    #結果をdistance(リスト)に格納する
    distance.append(x)
#距離情報にitem_id=53以外の映画のidを割り振る
distance1 = pd.Series(distance, index = others.item_id)

In [0]:
#結果
distance1

item_id
1       0.164128
2       0.098039
3       0.168102
4       0.278906
5       0.246647
          ...   
1656    0.140028
1658    0.000000
1662    0.000000
1664    0.080845
1674    0.000000
Length: 1446, dtype: float64

In [0]:
#item_id=53の映画に類似した映画10選を抽出
result = distance1.sort_values(ascending=False)[0:10]

In [0]:
result

item_id
219    0.380076
218    0.364516
92     0.350070
436    0.349531
200    0.349499
156    0.332272
56     0.326664
559    0.320064
17     0.306162
68     0.305656
dtype: float64

In [0]:
#データフレームを作成し、item_id列とsimilarity列を作成
result2 = pd.DataFrame({"item_id":list(result.index),
                  "similarity":result.values})

In [0]:
result2

item_id  similarity
0      219    0.380076
1      218    0.364516
2       92    0.350070
3      436    0.349531
4      200    0.349499
5      156    0.332272
6       56    0.326664
7      559    0.320064
8       17    0.306162
9       68    0.305656

In [0]:
d_item = pd.read_csv("ml-100k/u.item", sep='|',encoding="Latin1",header=None,usecols=[0,1,2,4])

In [0]:
d_item.head()

0  ...                                                  4
0  1  ...  http://us.imdb.com/M/title-exact?Toy%20Story%2...
1  2  ...  http://us.imdb.com/M/title-exact?GoldenEye%20(...
2  3  ...  http://us.imdb.com/M/title-exact?Four%20Rooms%...
3  4  ...  http://us.imdb.com/M/title-exact?Get%20Shorty%...
4  5  ...  http://us.imdb.com/M/title-exact?Copycat%20(1995)

[5 rows x 4 columns]

In [0]:
d_item.columns =   ["item_id","item_name","release_date","url"]

In [0]:
d_item.head()

item_id  ...                                                url
0        1  ...  http://us.imdb.com/M/title-exact?Toy%20Story%2...
1        2  ...  http://us.imdb.com/M/title-exact?GoldenEye%20(...
2        3  ...  http://us.imdb.com/M/title-exact?Four%20Rooms%...
3        4  ...  http://us.imdb.com/M/title-exact?Get%20Shorty%...
4        5  ...  http://us.imdb.com/M/title-exact?Copycat%20(1995)

[5 rows x 4 columns]

In [0]:
d_item.drop(labels=["release_date","url"], axis=1, inplace=True)

In [0]:
d_item.head()

item_id          item_name
0        1   Toy Story (1995)
1        2   GoldenEye (1995)
2        3  Four Rooms (1995)
3        4  Get Shorty (1995)
4        5     Copycat (1995)

In [0]:
result3 = pd.merge(result2, d_item, how='inner', on='item_id')

In [0]:
result3.head()

item_id  similarity                               item_name
0      219    0.380076       Nightmare on Elm Street, A (1984)
1      218    0.364516                        Cape Fear (1991)
2       92    0.350070                     True Romance (1993)
3      436    0.349531  American Werewolf in London, An (1981)
4      200    0.349499                     Shining, The (1980)

In [0]:
# 映画名を上からリストとして出力
list(result3.item_name)

['Nightmare on Elm Street, A (1984)',
 'Cape Fear (1991)',
 'True Romance (1993)',
 'American Werewolf in London, An (1981)',
 'Shining, The (1980)',
 'Reservoir Dogs (1992)',
 'Pulp Fiction (1994)',
 'Interview with the Vampire (1994)',
 'From Dusk Till Dawn (1996)',
 'Crow, The (1994)']